function formatDate(date: string) {
    var d = new Date(date),
        month = '' + (d.getMonth() + 1),
        day = '' + d.getDate(),
        year = d.getFullYear();

    if (month.length < 2)
        month = '0' + month;
    if (day.length < 2)
        day = '0' + day;

    return [year, month, day].join('-');
}

const date = formatDate('Sun May 11,2024');

export interface CardData {
  client_name: string,
  client_image: string
  profile_name: string,
  profile_image: string,
  title: string,
  total: number,
  done: number,
  comments: number,
  date: string,
  status: string,
}

const data: CardData[] = [
  {
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Completed",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Overdue",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Completed",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Overdue",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Completed",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: date,
    status: "To Do",
  },

]

export default data
