
interface CardData {
  client_name: string,
  client_image: string
  profile_name: string,
  profile_image: string,
  title: string,
  total: number,
  done: number,
  comments: number,
  date: Date,
  status: string,
}

const data: CardData = [
  {
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Completed",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Overdue",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Completed",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Overdue",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Doing",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Completed",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Under Review",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "Incomplete",
  },
{
    client_name: "Client Name",
    client_image: "/client-image.jpg",
    profile_name: "Profile Name",
    profile_image: "/profile-image.jpg",
    title: "Donec vitae dolor.  Cras placerat accumsan nulla.  ",
    comments: 45,
    total: 2,
    done:1,
    date: Date.now(),
    status: "To Do",
  },

]

export default data
